### PR TITLE
[Fix #39] Fix an incorrect autocorrect for `Minitest/AssertRespondTo`

### LINKED ISSUE #39: Minitest/AssertRespondTo autocorrect causes ArgumentError: wrong number of arguments (given 1, expected 2..3)
Given the test statement:

`assert respond_to? :token_payment_method`

The Minitest/AssertRespond cop auto corrects that to 

`assert_respond_to(:token_payment_method)`

When the test is run, an error message is returned: 

`ArgumentError: wrong number of arguments (given 1, expected 2..3)`

The log message is

`[Corrected] Minitest/AssertRespondTo: Prefer using assert_respond_to(:token_payment_method) over assert(respond_to? :token_payment_method).`

Minitest assert_respond_to requires an object:

> assert_respond_to(obj, meth, msg = nil)

This can be corrected by editing the corrected test statement to:

`assert_respond_to(self, :token_payment_method)`

Using Rails 6.01, Ruby 2.65, Minitest 5.13.0

### PR DESCRIPTION
**Pull request by koic**
Fixes #39.

This PR fixes an incorrect autocorrect for `Minitest/AssertRespondTo` and `Minitest/RefuteRespondTo` when using assertion method calling `respond_to` with receiver omitted.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop-minitest/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop-minitest/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/minitest/assert_respond_to.rb [hunk 1]
```diff
@@ -38,13 +37,20 @@ def autocorrect(node)
...
+              preferred = build_preferred_arguments(object, method, custom_message)
               replacement = "assert_respond_to(#{preferred})"
               corrector.replace(node.loc.expression, replacement)
             end
           end
         end
+
+        private
+
+        def build_preferred_arguments(receiver, method, message)
```
Comment (abhaynikam) [inline lib/rubocop/cop/minitest/assert_respond_to.rb]: @koic Since we are allowing `assert respond_to? :some_method`. Shouldn't we add the change in the example here: https://github.com/rubocop-hq/rubocop-minitest/pull/40/files#diff-8a61a4905f40fa4acda025d5ed4bbb66R9

WDYT?

Comment (koic) [reply lib/rubocop/cop/minitest/assert_respond_to.rb]: It seems that `assert(respond_to?(:some_method))` does not exist in the examples and documentation. What does that mean?

Comment (abhaynikam) [reply lib/rubocop/cop/minitest/assert_respond_to.rb]: I wanted to ask if we should update the example and documentation as follows

```
# Good
assert_respond_to(self, some_method)

# Bad
assert(respond_to?(:some_method))
```

Comment (koic) [reply lib/rubocop/cop/minitest/assert_respond_to.rb]: I get it! I updated the examples. Thanks for your explanation!
